public class DataFactory {
    /*public static void newCar(String name, Integer price, Id seller, Id brand, Date datePurchased, String region){    
        Car__c newCar = new Car__c();
        
        newCar.Name = name;
        newCar.Price__c = price;
        newCar.Seller__c = seller;
        newCar.Car_Brand__c = brand;
        newCar.Date_Purchased__c = datePurchased;
        newCar.Region__c = region;
        
        insert newCar;
    }*/
}